### PR TITLE
Update test_push.md

### PR DESCRIPTION
**Pull request by 0x41gilecat**

### CODE REVIEW

**Review by 0x41gilecat — COMMENTED** [review]
Test

**Review by hugo-syn — COMMENTED** [review]
test

**Review by 0x41gilecat — COMMENTED** [review]
Tests

**Review by hugo-syn — COMMENTED** [review]
test

**Review by hugo-syn — COMMENTED** [review]
test

**Review by hugo-syn — COMMENTED** [review]
nn

**Pull request closed without merging**
